# Uncomment this line to define a global platform for your project
platform :tvos, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'PulsetvOS' do
    pod 'Parse', :git => 'git@github.com:ParsePlatform/Parse-SDK-iOS-OSX.git', :branch => 'nlutsenko.tvos.podtest'
end

target 'PulsetvOSTests' do

end

target 'PulsetvOSUITests' do

end

