# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'PulsetvOS' do

end

target 'PulsetvOSTests' do

end

target 'PulsetvOSUITests' do

end

