# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'Parse'
pod 'Charts'
#pod 'Pushwoosh'
pod 'DeepLinkKit'
target 'PulseiOS' do

end

target 'PulseiOSTests' do

end

target 'PulseiOSUITests' do

end

